assortment/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('marketplace/', include("marketplace.urls")),
]

marketplace/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),

    path("categories", views.CategoryListView.as_view(), name="categories_list"),
    path("<categoryId>/attributes/<required>", views.AttributeListView.as_view(), name="attributes_list"),
    path("<attributeId>/attribute_values", views.AttributeValueListView.as_view(), name="attribute_values_list"),

    path("edit_category/<categoryId>", views.edit_category, name="edit_category_view"),
    path("edit_attribute/<attributeId>", views.edit_attribute, name="edit_attribute_view"),
    path("edit_attribute_value/<attributeValueId>", views.edit_attribute_value, name="edit_attribute_value_view"),

    path("export_xls", views.export_xls_config_view, name="export_xls_view"),
]

marketplace/models.py
from datetime import datetime

from django.db import models
import uuid

from marketplace.utils import execute_query


class Category(models.Model):
    # id = models.UUIDField(primary_key=True, default=uuid.uuid1, editable=False)
    # id = models.AutoField(primary_key=True, editable=False)

    categoryId = models.CharField(max_length=200, blank=True)
    categoryName = models.CharField(max_length=200, blank=True)
    orgId = models.CharField(max_length=200, blank=True)
    orgName = models.CharField("Org Name", max_length=200, blank=True)
    assortCategoryName = models.CharField(max_length=200, blank=True)
    assortCategoryRSXKey = models.CharField(max_length=200, blank=True)
    catConversionPlace = models.CharField(max_length=200, blank=True)
    catAddedToAssortment = models.BooleanField("Added to system?", blank=True)
    catIsActive = models.BooleanField("Is active?", blank=True, default=True)
    # catLastModified = models.DateTimeField("Last Modified", default=datetime.now, blank=True)
    catLastModified = models.CharField(max_length=200, blank=True)
    catNote = models.CharField("Note", max_length=200, blank=True)


class Attribute(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    # id = models.UUIDField(primary_key=True, default=uuid.uuid1, editable=False)
    # id = models.AutoField(primary_key=True, editable=False)

    required = models.BooleanField(editable=False)

    attributeName = models.CharField(max_length=200, blank=True)
    attributeId = models.CharField(max_length=200, blank=True)
    attributeDescription = models.CharField(max_length=200, blank=True)
    assortAttributeName = models.CharField(max_length=200, blank=True)
    assortAttributeRSXKey = models.CharField(max_length=200, blank=True)
    attrConversionPlace = models.CharField(max_length=200, blank=True)
    dataType = models.CharField(max_length=200, blank=True)
    minLength = models.CharField(max_length=200, null=True, blank=True)
    maxLength = models.CharField(max_length=200, null=True, blank=True)
    attrAddedToAssortment = models.BooleanField(blank=True)
    attrIsActive = models.BooleanField(default=True, blank=True)
    # attrLastModified = models.DateTimeField("Last Modified", default=datetime.now, blank=True)
    attrLastModified = models.CharField(max_length=200, blank=True)
    attrNote = models.CharField(max_length=200, blank=True)


class AttributeValue(models.Model):
    attribute = models.ForeignKey(Attribute, on_delete=models.CASCADE)

    # id = models.UUIDField(primary_key=True, default=uuid.uuid1, editable=False)
    # id = models.AutoField(primary_key=True, editable=False)

    valueName = models.CharField(max_length=200, blank=True)
    valueId = models.CharField(max_length=200, blank=True)
    assortValueName = models.CharField(max_length=200, blank=True)
    assortValueRSXKey = models.CharField(max_length=200, blank=True)
    valConversionPlace = models.CharField(max_length=200, blank=True)
    # valLastModified = models.DateTimeField("Last Modified", default=datetime.now, blank=True)
    valLastModified = models.CharField(max_length=200, blank=True)
    valAddedToAssortment = models.BooleanField(blank=True)
    valIsActive = models.BooleanField(default=True, blank=True)
    valNote = models.CharField(max_length=200, blank=True)


def query_db(search_values: dict, columns_to_select: list):
    print("search clauses")
    print(search_values)
    print("active_columns")
    print(columns_to_select)
    search_clauses = {'categoryId': 'Printer Paper', 'catAddedToAssortment': False, 'catIsActive': True}
    search_clauses = {'valueName': '100% Recycled Paper'}
    active_columns = ['categoryId', 'valueName']
    active_columns = ['valueId', 'valueName', 'attribute__attributeName']

    columns = ", ".join(columns_to_select)
    if not columns:
        columns = "*"

    def to_sql(value):
        if isinstance(value, bool):
            return f"{int(value)}"
        if isinstance(value, str):
            return f"'{value}'"
        return value

    where_clauses = " AND ".join([
        f"{key} = {to_sql(val)}"
        for key, val in search_values.items()
        if val != ''
    ])
    if where_clauses:
        where_clauses = f" WHERE {where_clauses}"
    print("where_clauses")
    print(where_clauses)

    query = f"""
    SELECT {columns} 
    FROM marketplace_category as category
     JOIN marketplace_attribute as attribute 
     ON attribute.category_id = category.id 
     JOIN marketplace_attributevalue as attribute_value 
     ON attribute.id = attribute_value.attribute_id 
    {where_clauses}
    """
    print(query)
    result = execute_query(query)
    return result

marketplace/forms.py
from django.forms import (
    ModelForm,
    forms,
    fields,
    TextInput,
    BaseFormSet,
    formset_factory,
)
from marketplace.models import (
    Category,
    Attribute,
    AttributeValue,
)


class CategoryForm(ModelForm):
    # catIsActive = fields.CharField()

    class Meta:
        model = Category
        fields = '__all__'
        widgets = {
            'categoryId': TextInput(attrs={'readonly': 'readonly'}),
            'categoryName': TextInput(attrs={'readonly': 'readonly'}),
            'orgId': TextInput(attrs={'readonly': 'readonly'}),
            'orgName': TextInput(attrs={'readonly': 'readonly'}),
            'catLastModified': TextInput(attrs={'readonly': 'readonly'}),
        }


class AttributeForm(ModelForm):
    class Meta:
        model = Attribute
        fields = '__all__'
        widgets = {
            'attributeName': TextInput(attrs={'readonly': 'readonly'}),
            'attributeId': TextInput(attrs={'readonly': 'readonly'}),
            'attributeDescription': TextInput(attrs={'readonly': 'readonly'}),
            'dataType': TextInput(attrs={'readonly': 'readonly'}),
            'attrIsActive': TextInput(attrs={'readonly': 'readonly'}),
            'attrLastModified': TextInput(attrs={'readonly': 'readonly'}),
            'category': TextInput(attrs={'readonly': 'readonly'}),
        }


class AttributeValueForm(ModelForm):
    class Meta:
        model = AttributeValue
        fields = '__all__'
        widgets = {
            'attribute': TextInput(attrs={'readonly': 'readonly'}),
            'valueName': TextInput(attrs={'readonly': 'readonly'}),
            'valueId': TextInput(attrs={'readonly': 'readonly'}),
            'valLastModified': TextInput(attrs={'readonly': 'readonly'}),
            'valAddedToAssortment': TextInput(attrs={'readonly': 'readonly'}),
            # 'valNote': TextInput(attrs={'readonly': 'readonly'}),
        }


class CategorySearchForm(ModelForm):
    class Meta:
        model = Category
        exclude = ["id"]
        widgets = {
        }


class AttributeSearchForm(ModelForm):
    class Meta:
        model = Attribute
        exclude = ["id", "category"]
        widgets = {
        }


class AttributeValueSearchForm(ModelForm):
    class Meta:
        model = AttributeValue
        exclude = ["id", "attribute"]
        widgets = {
        }


class XlsColumnsForm(BaseFormSet):
    def add_fields(self, form, index):
        super().add_fields(form, index)
        bool_field = lambda: fields.BooleanField(label=field.label, required=False)
        for field_name, field in CategoryForm().fields.items():
            form.fields[f"category.{field_name}"] = bool_field()
        for field_name, field in AttributeForm().fields.items():
            form.fields[f"attribute.{field_name}"] = bool_field()
        for field_name, field in AttributeValueForm().fields.items():
            form.fields[f"attribute_value.{field_name}"] = bool_field()


XlsColumnsFormSet = formset_factory(forms.Form, formset=XlsColumnsForm)

marketplace/views.py
from django.http import HttpResponse, HttpRequest
from django.views.generic import (
    ListView,
    UpdateView,
    DetailView
)
from django.shortcuts import render, redirect
from django.urls import reverse


from marketplace import models
from marketplace import forms


def index(request):
    return HttpResponse("Hello, you're in marketplace")


class CategoryListView(ListView):
    model = models.Category

    def get_queryset(self):
        f = forms.CategorySearchForm(self.request.GET)
        f.is_valid()
        not_empty_params_dict = dict(filter(lambda kv: kv[1] != '', f.cleaned_data.items()))

        return self.model.objects.filter(
            **not_empty_params_dict
        )

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_form"] = forms.CategorySearchForm(self.request.GET)
        return context


class AttributeListView(ListView):
    model = models.Attribute

    def get_queryset(self):
        f = forms.AttributeSearchForm(self.request.GET)
        f.is_valid()
        not_empty_params_dict = dict(filter(lambda kv: kv[1] != '', f.cleaned_data.items()))

        if self.kwargs.get("required") == "required":
            is_required = True
        else:
            is_required = False
        return self.model.objects.filter(
            category__pk=self.kwargs["categoryId"],
            required=is_required,
            **not_empty_params_dict,
        )

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_form"] = forms.AttributeSearchForm(self.request.GET)
        return context


class AttributeValueListView(ListView):
    model = models.AttributeValue

    def get_queryset(self):
        f = forms.AttributeValueSearchForm(self.request.GET)
        f.is_valid()
        not_empty_params_dict = dict(filter(lambda kv: kv[1] != '', f.cleaned_data.items()))

        return self.model.objects.filter(
            attribute__pk=self.kwargs["attributeId"],
            **not_empty_params_dict,
        )

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_form"] = forms.AttributeValueSearchForm(self.request.GET)
        return context


def edit_category(request: HttpRequest, categoryId):
    if request.method == "POST":
        form = forms.CategoryForm(
            request.POST,
            instance=models.Category.objects.get(pk=categoryId)
        )
        if form.is_valid():
            form.save()
            return redirect("categories_list")
    else:
        form = forms.CategoryForm(instance=models.Category.objects.get(pk=categoryId))
    return render(request, "marketplace/edit_category.html", {"form": form})


def edit_attribute(request: HttpRequest, attributeId):
    model_instance = models.Attribute.objects.get(pk=attributeId)
    if request.method == "POST":
        form = forms.AttributeForm(
            request.POST,
            instance=model_instance
        )
        if form.is_valid():
            form.save()
            return redirect(reverse("attributes_list", args=(model_instance.category.id, model_instance.required)))
    else:
        form = forms.AttributeForm(instance=model_instance)
    return render(request, "marketplace/edit_attribute.html", {"form": form})


def edit_attribute_value(request: HttpRequest, attributeValueId):
    model_instance = models.AttributeValue.objects.get(pk=attributeValueId)
    if request.method == "POST":
        form = forms.AttributeValueForm(
            request.POST,
            instance=model_instance
        )
        if form.is_valid():
            form.save()
            return redirect(reverse("attribute_values_list", args=(model_instance.attribute.id,)))
    else:
        form = forms.AttributeValueForm(instance=model_instance)
    return render(request, "marketplace/edit_attribute_value.html", {"form": form})


def export_xls_config_view(request):
    import json
    from django.core import serializers
    from marketplace.utils import save_excel
    if request.method == "POST":
        category_form = forms.CategorySearchForm(request.POST, prefix="category")
        attribute_form = forms.AttributeSearchForm(request.POST, prefix="attribute")
        attribute_values_form = forms.AttributeValueSearchForm(request.POST, prefix="attribute_value")
        columns_config_form = forms.XlsColumnsFormSet(request.POST)
        if columns_config_form.is_valid() \
                and category_form.is_valid()\
                and attribute_form.is_valid()\
                and attribute_values_form.is_valid():
            # not_empty_params_dict = dict(filter(lambda kv: kv[1] != '', category_form.cleaned_data.items()))
            active_columns = [column_name
                              for column_name, column_status in columns_config_form.forms[0].cleaned_data.items()
                              if column_status]

            with open("/Users/volodymyr/dev/assortment/dump.json", "w") as file:
                result = models.query_db(category_form.cleaned_data, active_columns)
                save_excel(result, included_header=active_columns)
                # json.dump([v for v in result], file)

    return render(request, 'marketplace/export_xls.html',
                  {
                      "category_form": forms.CategorySearchForm(prefix="category"),
                      "attribute_form": forms.AttributeSearchForm(prefix="attribute"),
                      "attribute_values_form": forms.AttributeValueSearchForm(prefix="attribute_value"),

                      "columns_config_form": forms.XlsColumnsFormSet()
                  }
                  )

templates/marketplace/attributeValue_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Attr Values</title>
</head>
<body>
<form>
    {{ search_form }}
    <input type="submit" value="SEARCH">
</form>
{% block content %}
<table border="1">
    <thead>
    <tr>
        <th></th>
        <th>valueName</th>
        <th>valueId</th>
        <th>assortValueName</th>
        <th>assortValueRSXKey</th>
        <th>valConversionPlace</th>
        <th>valLastModified</th>
        <th>valAddedToAssortment</th>
        <th>valIsActive</th>
        <th>valNote</th>
    </tr>
    </thead>
    <tbody>
    {% for value in attributevalue_list %}
    <tr>
        <td>
            <a href="/marketplace/edit_attribute_value/{{ value.id }}">
                edit
            </a>
        </td>
        <td> {{ value.valueName }}</td>
        <td> {{ value.valueId }}</td>
        <td> {{ value.assortValueName }}</td>
        <td> {{ value.assortValueRSXKey }}</td>
        <td> {{ value.valConversionPlace }}</td>
        <td> {{ value.valLastModified }}</td>
        <td> {{ value.valAddedToAssortment }}</td>
        <td> {{ value.valIsActive }}</td>
        <td> {{ value.valNote }}</td>
    </tr>

    {% endfor %}
    </tbody>
</table>
{% endblock %}
</body>
</html>

templates/marketplace/attribute_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Attributes</title>
</head>
<body>
<form>
    {{ search_form }}
    <input type="submit" value="SEARCH">
</form>
{% block content %}
<table border="1">
    <thead>
    <tr>
        <th></th>
        <th>attributeName</th>
        <th>attributeId</th>
        <th>attributeDescription</th>
        <th>assortAttributeName</th>
        <th>assortAttributeRSXKey</th>
        <th>attrConversionPlace</th>
        <th>dataType</th>
        <th>minLength</th>
        <th>maxLength</th>
        <th>attrAddedToAssortment</th>
        <th>attrIsActive</th>
        <th>attrNote</th>
    </tr>
    </thead>
    <tbody>
    {% for attribute in attribute_list %}
    <tr>
        <td>
            <a href="/marketplace/edit_attribute/{{ attribute.id }}">
                edit
            </a>
        </td>
        <td> {{ attribute.attributeName }}</td>
        <td> {{ attribute.attributeId }}</td>
        <td> {{ attribute.attributeDescription }}</td>
        <td> {{ attribute.assortAttributeName }}</td>
        <td> {{ attribute.assortAttributeRSXKey }}</td>
        <td> {{ attribute.attrConversionPlace }}</td>
        <td> {{ attribute.dataType }}</td>
        <td> {{ attribute.minLength }}</td>
        <td> {{ attribute.maxLength }}</td>
        <td> {{ attribute.attrAddedToAssortment }}</td>
        <td> {{ attribute.attrIsActive }}</td>
        <td> {{ attribute.attrNote }}</td>
        <td>
            <a href="/marketplace/{{ attribute.id}}/attribute_values">
                VALUES
            </a>
        </td>
    </tr>

    {% endfor %}
    </tbody>
</table>
{% endblock %}
</body>
</html>

templates/marketplace/category_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Categories</title>
</head>
<body>
<form>
    {{ search_form }}
    <input type="submit" value="SEARCH">
</form>
{% block content %}
<table border="1">
    <thead>
    <tr>
        <th></th>
        <th>categoryId</th>
        <th>categoryName</th>
        <th>orgId</th>
        <th>orgName</th>
        <th>assortCategoryName</th>
        <th>assortCategoryRSXKey</th>
        <th>catConversionPlace</th>
        <th>catAddedToAssortment</th>
        <th>catIsActive</th>
        <th>catLastModified</th>
        <th>catNote</th>
        <th>attributes</th>
    </tr>
    </thead>
    <tbody>
    {% for category in category_list %}
    <tr>
        <td>
            <a href="/marketplace/edit_category/{{ category.id }}">
                edit
            </a>
        </td>
        <td> {{ category.categoryId }}</td>
        <td> {{ category.categoryName }}</td>
        <td> {{ category.orgId }}</td>
        <td> {{ category.orgName }}</td>
        <td> {{ category.assortCategoryName }}</td>
        <td> {{ category.assortCategoryRSXKey }}</td>
        <td> {{ category.catConversionPlace }}</td>
        <td> {{ category.catAddedToAssortment }}</td>
        <td> {{ category.catIsActive }}</td>
        <td> {{ category.catLastModified }}</td>
        <td> {{ category.catNote }}</td>
        <td>
            <a href="/marketplace/{{ category.id}}/attributes/required">
                REQUIRED ATTRIBUTES
            </a>
        </td>
        <td>
            <a href="/marketplace/{{ category.id}}/attributes/optional">
                OPTIONAL ATTRIBUTES
            </a>
        </td>

    </tr>

    {% endfor %}
    </tbody>
</table>
{% endblock %}
</body>
</html>

templates/marketplace/edit_attribute.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Attribute</title>
</head>
<body>
<form method="POST">
{% csrf_token %}
{{ form }}
<input type="submit" value="SAVE">
</form>
</body>
</html>

templates/marketplace/edit_attribute_value.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Attribute Value</title>
</head>
<body>
<form method="POST">
{% csrf_token %}
{{ form }}
<input type="submit" value="SAVE">
</form>
</body>
</html>

templates/marketplace/edit_category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Category</title>
</head>
<body>
<form method="POST">
{% csrf_token %}
{{ form }}
<input type="submit" value="SAVE">
</form>
</body>
</html>

templates/marketplace/export_xls.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Export XLS</title>
</head>
<body>
<form method="POST">
    {% csrf_token %}
<!--    <form name="filter_values">-->

        {{ category_form }}
        {{ attribute_form }}
        {{ attribute_values_form }}
<!--    </form>-->
<!--    <form name="columns_config">-->
        <h2>Columns Config</h2>

    {{ columns_config_form.management_form }}
    {% for form in columns_config_form %}{{ form.as_div }}{% endfor %}
<!--        {% for field, label in  columns_config_form.category_fields.items %}-->
<!--    <label>-->
<!--        {{label }}-->

<!--    <input type="checkbox"-->
<!--                    name="{{field }}">-->
<!--    </label>-->

<!--        {% endfor %}-->
    <input type="submit" value="EXPORT XLS">
<!--    </form>-->
</form>
</body>
</html>